name: Sincronizar Submódulos

on:
  # Permite ejecutar el workflow manualmente desde la pestaña Actions de GitHub
  workflow_dispatch:

  # Revisa y actualiza automáticamente según la programación
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora en el minuto 0

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Otorga permisos para hacer push al repositorio

    steps:
      - name: Descargar el repositorio principal con submódulos
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Actualizar submódulos a la última versión de main
        run: |
          git submodule update --remote --merge

      - name: Configurar usuario Git y subir cambios si existen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if [[ -n $(git status --porcelain) ]]; then
            git commit -am "chore: actualizar referencias de submódulos"
            git push
          else
            echo "No hay actualizaciones pendientes en los submódulos."
          fi